swagger: '2.0'

info:
  version: "0.0.2"
  title: LoginAPI
  description: The LoginAPI allows to generate tokens based on either third party credentials or previously minted tokens
paths:
  /login:
    get:
      description: Mints a session token for a given username if the authentication provider responds to the challenge positively
      parameters:
        - name: username
          in: query
          description: The user being authenticated
          required: true
          type: string
        - name: challenge
          in: query
          description: The challenge that gets passed to the authentication provider for validation
          required: true
          type: string
        - name: provider
          in: query
          description: Authentication provider the incoming credentials should be validated against. The provider must be able to provide yes/no answers based on the credentials provided. 
          required: true
          type: string
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            title: Token
            type: string
        400:
          description: One of the required parameters was missing
        401:
          description: The credentials were not accepted by the authentication provider or the authentication provider was unknown
  /reissue:
    get:
      description: Re-issues a token based on an existing one passed as a bearer token
      responses:
        200:
          description: Successful response
          schema:
            title: Token
            type: string
        401:
          description: The token passed was invalid
