language: go

go:
  - 1.5

install:
  - ls -Al
  - pwd
  - export GOPATH=$PWD
  - go get -d github.com/e-gov/fox/fox/foxservice github.com/e-gov/fox/login/loginservice
  - go get -d github.com/onsi/ginkgo
  - go get -d github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$GOPATH/bin

script:
  - mkdir src/github.com/e-gov/fox/fox/fox_test/foxdb/
  - ginkgo src/github.com/e-gov/fox/login/login_test/
  - ginkgo src/github.com/e-gov/fox/fox/fox_test/
  - ginkgo src/github.com/e-gov/fox/authn/authn_test/
  - ginkgo src/github.com/e-gov/fox/authz/authz_test/
