language: go

go:
        - 1.5

install:
        - go get fox/main
        - go get login/main
        - go get github.com/onsi/ginkgo
        - go get go get github.com/onsi/ginkgo
        - go get github.com/onsi/gomega

script:
        - ginkgo src/login/login_test/
        - ginkgo src/fox/fox_test/
