language: go

go:
        - 1.5

install:
        - ls -Al
        - go get github.com/e-gov/fox/main
        - go get github.com/e-gov/login/main
        - go get github.com/onsi/ginkgo
        - go get github.com/onsi/gomega

script:
        - ginkgo src/github.com/e-gov/login/login_test/
        - ginkgo src/github.com/e-gov/fox/fox_test/
