language: go

go:
        - 1.5

install:
        - ls -Al
        - pwd
        - export GOPATH=$PWD
        - go get fox/main
        - go get login/main
        - go get github.com/onsi/ginkgo
        - go get github.com/onsi/gomega

script:
        - ginkgo login/login_test/
        - ginkgo fox/fox_test/
