language: go

go:
        - 1.5

install:
        - ls -Al
        - pwd
        - export GOPATH=$PWD
        - go get fox/main
        - go get login/main
        - go get github.com/onsi/ginkgo
        - go get github.com/onsi/gomega
        - go install github.com/onsi/ginkgo/ginkgo
        - export PATH=$PATH:$GOPATH/bin

script:
        - mkdir foxdb
        - ginkgo src/login/login_test/
        - ginkgo src/fox/fox_test/
