language: go

go:
        - 1.5

install:
        - ls -Al
        - pwd
        - export GOPATH=$PWD
        - go get -d fox/foxservice login/loginservice
        - go get -d github.com/onsi/ginkgo
        - go get -d github.com/onsi/gomega
        - go install github.com/onsi/ginkgo/ginkgo
        - export PATH=$PATH:$GOPATH/bin

script:
        - mkdir src/fox/fox_test/foxdb/
        - ginkgo src/login/login_test/
        - ginkgo src/fox/fox_test/
        - ginkgo src/authn/authn_test/
