version: '2'
services:
  main:
    build:
     context: .
     dockerfile: ./static/Dockerfile
#    volumes:
#     - npm_data:/statc/node_modules/

volumes:
  npm_data:
    driver: local-persist
    driver_opts:
      mountpoint: ./static/node_modules/
