version: '2'
services:
  front_end:
    build:
     context: .
     dockerfile: ./static/Dockerfile
    volumes:
      - npm_data:/statc/node_modules/
  fox:
    build:
     context: .
     dockerfile: ./src/github.com/e-gov/fox/fox/Dockerfile
  login:
    build:
     context: .
     dockerfile: ./src/github.com/e-gov/fox/login/Dockerfile
  haproxy:
    build:
     context: .
     dockerfile: ./haproxy/Dockerfile

volumes:
  npm_data:
    driver: local-persist
    driver_opts:
      mountpoint: ./static/node_modules/

