version: '2'
services:
  static_web:
    build:
     context: .
     dockerfile: ./static/Dockerfile
    depends_on:
     - fox_LB
    networks:
     - static_nw
     - fox_lb_nw
  fox:
    build:
     context: .
     dockerfile: ./src/github.com/e-gov/fox/fox/Dockerfile
    volumes:
     - config-data:/config/:ro
    networks:
     - fox_nw
  session:
    build:
     context: .
     dockerfile: ./src/github.com/e-gov/fox/login/Dockerfile
    volumes:
     - config-data:/config/
    networks:
     - session_nw
  fox_LB:
    image: haproxy:1.6
    depends_on:
     - fox
     - session
    volumes:
     - ./config/fox_LB/fox_LB_hap.cfg:/usr/local/etc/haproxy/haproxy.cfg
     - /dev/log:/dev/log
    networks:
     - fox_nw
     - session_nw
     - fox_lb_nw
    ports:
     - "70:70"
  content_LB:
    image: haproxy:1.6
    depends_on:
     - static_web
    volumes:
     - ./config/content_LB/content_LB_hap.cfg:/usr/local/etc/haproxy/haproxy.cfg
     - /dev/log:/dev/log
    networks:
     - static_nw
     - fox_lb_nw
    ports:
     - "9000:9000"
     - "71:71"

volumes:
  config-data:
    driver: local

networks:
  session_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.28.0.0/16
  fox_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.29.0.0/16
  static_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.30.0.0/16
  fox_lb_nw:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.31.0.0/16
