# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Fox Registry
email: andres.kutt@ria.ee
description: > # this means to ignore newlines until "baseurl:"
  Fox Registry is a sample application intended to serve as a test bed
  for extracting a reference archcitecture for simple applications that can be
  deployed to the cloud
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
