swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: LoginAPI

# Describe your paths here
paths:
  /login:
    get:
      description: Mints a session token for a given username
      parameters:
        - name: credentials
          in: query
          description: The credentials to validate against a third party so a token can be minted. Can, for example, contain a json structure with username and password
          required: true
          type: string
        - name: provider
          in: query
          description: Authentication provider the incoming credentials should be validated against. The provider must be able to provide yes/no answers based on the credentials provided
          required: true
          type: string
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            title: Token
            type: string
        401:
          description: The credentials were not accepted by the authentication provider
